name: wargawargiapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  share_plus: ^7.2.0              # Share functionality
  provider: ^6.1.1              # State Management global
  intl: ^0.19.0                 # Formatting Tanggal Indonesia & Waktu Surat
  uuid: ^4.3.3                  # Generator ID unik otomatis untuk arsip surat
  google_fonts: ^6.1.0  
  image_picker: ^1.0.7
  geolocator: ^13.0.2
  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.8
<<<<<<< HEAD
  sqlite_viewer: ^1.0.5
  pdf: ^3.11.2
  printing: ^5.14.2
=======
  pdf: ^3.12.0
  printing: ^5.14.3
  url_launcher: ^6.3.2
  qr_flutter: ^4.1.0
>>>>>>> 473903b86224efca4f8243e756b40516a3c8a1cb

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  