name: wargawargiapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.5+4
  shared_preferences: ^2.2.2
  provider: ^6.1.1              # State Management global
  intl: ^0.19.0                 # Formatting Tanggal Indonesia & Waktu Surat
  uuid: ^4.3.3                  # Generator ID unik otomatis untuk arsip surat
  google_fonts: ^6.1.0  
  image_picker: ^1.0.7


  cupertino_icons: ^1.0.8
  sqlite_viewer: ^1.0.5
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  